require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  Exclude:
    - 'bin/**/*'
  NewCops: enable
  TargetRubyVersion: 2.6.0

Layout/LineLength:
  Max: 120

Metrics/AbcSize:
  Max: 30

Metrics/BlockLength:
  Max: 50

Metrics/ClassLength:
  Max: 500

Metrics/MethodLength:
  Max: 50

RSpec/ExampleLength:
  Max: 20

RSpec/MultipleMemoizedHelpers:
  Max: 20

RSpec/NestedGroups:
  Max: 5

Style/Documentation:
  Enabled: false
